version: '3.8'

services:
  web:
    build: .
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - frontend
    env_file:
      - .env

  frontend:
    build: .
    command: ["streamlit", "run", "app.py"]
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
