version: '3.8'

services:
  api:
    build: .
    command: ["uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: .
    command: ["python", "-m", "streamlit", "run", "frontend/app.py"]
    ports:
      - "8501:8501"
